# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = "blowfish"
baseURL = "https://indiecrew-studio.github.io/"
defaultContentLanguage = "vi"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

buildDrafts = false
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"

[taxonomies]
  tag = "Thẻ"
  category = "Chuyên mục"
  author = "Tác giả"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
